- name: ansiblep laybook control
  host: frontend
  become: yes
  task:
  - name : install nginx if RedHat
    ansible.builtin.dnf:
      name: nginx
      state: present
      when: ansible_os_family == "RedHat"
  - name: install nginx if debian
    name: nginx
    state: present
    when: ansible_os_family == "Debian"