- name: installing packages
  hosts: backend
  become: yes
  tasks:
    - name: Install multiple packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - mysql
        - zip
