- name: installig
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
  ansible.bulitin.package:
    name: "{{ item}}"
    state: install
    loop:
    - nginx
    - mysql
    - zip


